import { GoogleGenAI, Modality, Chat } from "@google/genai";

const API_KEY = process.env.API_KEY;

if (!API_KEY) {
  throw new Error("API_KEY environment variable not set");
}

const ai = new GoogleGenAI({ apiKey: API_KEY });

const fileToGenerativePart = (file: File) => {
  return new Promise<{ mimeType: string; data: string }>((resolve, reject) => {
    const reader = new FileReader();
    reader.onload = () => {
      if (typeof reader.result !== 'string') {
        return reject(new Error("Failed to read file as base64 string."));
      }
      const base64Data = reader.result.split(',')[1];
      resolve({
        mimeType: file.type,
        data: base64Data,
      });
    };
    reader.onerror = (error) => reject(error);
    reader.readAsDataURL(file);
  });
};

export const virtualTryOn = async (userImageFile: File, productImageUrl: string): Promise<string> => {
  try {
    const userImagePart = await fileToGenerativePart(userImageFile);

    const response = await fetch(productImageUrl);
    if (!response.ok) throw new Error("Failed to fetch product image.");
    const blob = await response.blob();
    const productFile = new File([blob], "product.jpg", { type: blob.type });
    const productImagePart = await fileToGenerativePart(productFile);

    const result = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image-preview',
        contents: {
          parts: [
            { inlineData: userImagePart },
            { inlineData: productImagePart },
            { text: "Act as an expert virtual stylist and digital fashion artist. Your task is to create a high-fashion, magazine-quality image by flawlessly superimposing the clothing from the second image (the product) onto the person in the first image (the model). The result must be stylish, empowering, and photorealistic. Pay meticulous attention to: 1. **Dynamic Draping:** The clothing must follow the model's unique pose and body contours with natural-looking folds and movement. 2. **Harmonious Lighting & Shadows:** The lighting on the garment must blend perfectly with the ambient light on the model. Generate soft, realistic shadows to create depth and dimension. 3. **Model Integrity:** The model's original body shape, pose, skin tone, and hair must be preserved perfectly. 4. **Thematic Background:** Replace the original background with a beautiful, high-resolution cosmic starry nebula in shades of dark blue, purple, and glowing pink to match the store's aesthetic. 5. **Final Output:** The output must ONLY be the edited image file. Do not include any text, logos, or commentary." },
          ],
        },
        config: {
            responseModalities: [Modality.IMAGE, Modality.TEXT],
        },
    });

    for (const part of result.candidates[0].content.parts) {
      if (part.inlineData) {
        return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
      }
    }
    throw new Error("No image was generated by the model.");

  } catch (error) {
    console.error("Error during virtual try-on:", error);
    throw new Error("Failed to perform virtual try-on.");
  }
};


export const startNyraChat = (): Chat => {
    return ai.chats.create({
        model: 'gemini-2.5-flash',
        config: {
            systemInstruction: "You are Nyra, an AI stylist for 'Black & Pink Thrift Store,' a futuristic, female-centric thrift shop. Your personality is a playful, stylish, and supportive mix of an angel and a devil. You're sassy but helpful. Keep your answers concise, fashionable, and use emojis like 💖, ✨, 😈, 😇. You can answer questions about product prices, sizes, shipping, and give styling advice. The store's vibe is 'cosmic goth meets bubblegum pop'.",
        },
    });
};
